In [12]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import seaborn as sns

In [13]:
df = pd.read_csv('50_Startups.csv')
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [14]:
df['State'].value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

In [15]:
from sklearn.preprocessing import OneHotEncoder
cat_cols  = ['State']
ohe = OneHotEncoder(drop='first')
X_encoded = ohe.fit_transform(df[cat_cols]).toarray()
X_encoded_df = pd.DataFrame(X_encoded, columns=ohe.get_feature_names_out(cat_cols))
X_encoded_df

    State_Florida  State_New York
0             0.0             1.0
1             0.0             0.0
2             1.0             0.0
3             0.0             1.0
4             1.0             0.0
5             0.0             1.0
6             0.0             0.0
7             1.0             0.0
8             0.0             1.0
9             0.0             0.0
10            1.0             0.0
11            0.0             0.0
12            1.0             0.0
13            0.0             0.0
14            1.0             0.0
15            0.0             1.0
16            0.0             0.0
17            0.0             1.0
18            1.0             0.0
19            0.0             1.0
20            0.0             0.0
21            0.0             1.0
22            1.0             0.0
23            1.0             0.0
24            0.0             1.0
25            0.0             0.0
26            1.0             0.0
27            0.0             1.0
28            1.0             0.0
29            0.0             1.0
30            1.0             0.0
31            0.0             1.0
32            0.0             0.0
33            1.0             0.0
34            0.0             0.0
35            0.0             1.0
36            1.0             0.0
37            0.0             0.0
38            0.0             1.0
39            0.0             0.0
40            0.0             0.0
41            1.0             0.0
42            0.0             0.0
43            0.0             1.0
44            0.0             0.0
45            0.0             1.0
46            1.0             0.0
47            0.0             0.0
48            0.0             1.0
49            0.0             0.0

In [16]:
clean_df = pd.concat([df, X_encoded_df], axis=1).drop(cat_cols, axis=1)
clean_df

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0.0,1.0
1,162597.70,151377.59,443898.53,191792.06,0.0,0.0
2,153441.51,101145.55,407934.54,191050.39,1.0,0.0
3,144372.41,118671.85,383199.62,182901.99,0.0,1.0
4,142107.34,91391.77,366168.42,166187.94,1.0,0.0
5,131876.90,99814.71,362861.36,156991.12,0.0,1.0
6,134615.46,147198.87,127716.82,156122.51,0.0,0.0
7,130298.13,145530.06,323876.68,155752.60,1.0,0.0
8,120542.52,148718.95,311613.29,152211.77,0.0,1.0
9,123334.88,108679.17,304981.62,149759.96,0.0,0.0
10,101913.08,110594.11,229160.95,146121.95,1.0,0.0
11,100671.96,91790.61,249744.55,144259.40,0.0,0.0
12,93863.75,127320.38,249839.44,141585.52,1.0,0.0
13,91992.39,135495.07,252664.93,134307.35,0.0,0.0
14,119943.24,156547.42,256512.92,132602.65,1.0,0.0
15,114523.61,122616.84,261776.23,129917.04,0.0,1.0
16,78013.11,121597.55,264346.06,126992.93,0.0,0.0
17,94657.16,145077.58,282574.31,125370.37,0.0,1.0
18,91749.16,114175.79,294919.57,124266.90,1.0,0.0
19,86419.70,153514.11,0.00,122776.86,0.0,1.0
20,76253.86,113867.30,298664.47,118474.03,0.0,0.0
21,78389.47,153773.43,299737.29,111313.02,0.0,1.0
22,73994.56,122782.75,303319.26,110352.25,1.0,0.0
23,67532.53,105751.03,304768.73,108733.99,1.0,0.0
24,77044.01,99281.34,140574.81,108552.04,0.0,1.0
25,64664.71,139553.16,137962.62,107404.34,0.0,0.0
26,75328.87,144135.98,134050.07,105733.54,1.0,0.0
27,72107.60,127864.55,353183.81,105008.31,0.0,1.0
28,66051.52,182645.56,118148.20,103282.38,1.0,0.0
29,65605.48,153032.06,107138.38,101004.64,0.0,1.0
30,61994.48,115641.28,91131.24,99937.59,1.0,0.0
31,61136.38,152701.92,88218.23,97483.56,0.0,1.0
32,63408.86,129219.61,46085.25,97427.84,0.0,0.0
33,55493.95,103057.49,214634.81,96778.92,1.0,0.0
34,46426.07,157693.92,210797.67,96712.80,0.0,0.0
35,46014.02,85047.44,205517.64,96479.51,0.0,1.0
36,28663.76,127056.21,201126.82,90708.19,1.0,0.0
37,44069.95,51283.14,197029.42,89949.14,0.0,0.0
38,20229.59,65947.93,185265.10,81229.06,0.0,1.0
39,38558.51,82982.09,174999.30,81005.76,0.0,0.0
40,28754.33,118546.05,172795.67,78239.91,0.0,0.0
41,27892.92,84710.77,164470.71,77798.83,1.0,0.0
42,23640.93,96189.63,148001.11,71498.49,0.0,0.0
43,15505.73,127382.30,35534.17,69758.98,0.0,1.0
44,22177.74,154806.14,28334.72,65200.33,0.0,0.0
45,1000.23,124153.04,1903.93,64926.08,0.0,1.0
46,1315.46,115816.21,297114.46,49490.75,1.0,0.0
47,0.00,135426.92,0.00,42559.73,0.0,0.0
48,542.05,51743.15,0.00,35673.41,0.0,1.0
49,0.00,116983.80,45173.06,14681.40,0.0,0.0

In [17]:
from sklearn.preprocessing import StandardScaler
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
scaler = StandardScaler()
clean_df[num_cols] = scaler.fit_transform(clean_df[num_cols])
clean_df

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,2.016411,0.560753,2.153943,2.011203,0.0,1.0
1,1.955860,1.082807,1.923600,1.999430,0.0,0.0
2,1.754364,-0.728257,1.626528,1.980842,1.0,0.0
3,1.554784,-0.096365,1.422210,1.776627,0.0,1.0
4,1.504937,-1.079919,1.281528,1.357740,1.0,0.0
5,1.279800,-0.776239,1.254210,1.127250,0.0,1.0
6,1.340066,0.932147,-0.688150,1.105481,0.0,0.0
7,1.245057,0.871980,0.932186,1.096210,1.0,0.0
8,1.030369,0.986952,0.830887,1.007470,0.0,1.0
9,1.091819,-0.456640,0.776107,0.946022,0.0,0.0
10,0.620398,-0.387599,0.149807,0.854847,1.0,0.0
11,0.593085,-1.065540,0.319834,0.808168,0.0,0.0
12,0.443260,0.215449,0.320617,0.741155,1.0,0.0
13,0.402078,0.510179,0.343957,0.558750,0.0,0.0
14,1.017181,1.269199,0.375742,0.516026,1.0,0.0
15,0.897913,0.045868,0.419219,0.448720,0.0,1.0
16,0.094441,0.009118,0.440446,0.375436,0.0,0.0
17,0.460720,0.855666,0.591017,0.334771,0.0,1.0
18,0.396725,-0.258465,0.692992,0.307116,1.0,0.0
19,0.279442,1.159837,-1.743127,0.269773,0.0,1.0
20,0.055726,-0.269588,0.723926,0.161935,0.0,0.0
21,0.102724,1.169186,0.732788,-0.017534,0.0,1.0
22,0.006007,0.051850,0.762376,-0.041613,1.0,0.0
23,-0.136201,-0.562211,0.774349,-0.082169,1.0,0.0
24,0.073115,-0.795469,-0.581939,-0.086729,0.0,1.0
25,-0.199312,0.656489,-0.603517,-0.115493,0.0,0.0
26,0.035370,0.821718,-0.635835,-0.157367,1.0,0.0
27,-0.035519,0.235069,1.174271,-0.175542,0.0,1.0
28,-0.168793,2.210141,-0.767189,-0.218798,1.0,0.0
29,-0.178609,1.142457,-0.858134,-0.275882,0.0,1.0
30,-0.258074,-0.205629,-0.990357,-0.302625,1.0,0.0
31,-0.276958,1.130554,-1.014419,-0.364127,0.0,1.0
32,-0.226949,0.283924,-1.362450,-0.365524,0.0,0.0
33,-0.401129,-0.659324,0.029817,-0.381787,1.0,0.0
34,-0.600682,1.310535,-0.001879,-0.383444,0.0,0.0
35,-0.609750,-1.308658,-0.045493,-0.389291,0.0,1.0
36,-0.991570,0.205925,-0.081763,-0.533932,1.0,0.0
37,-0.652532,-2.525994,-0.115608,-0.552955,0.0,0.0
38,-1.177178,-1.997270,-0.212785,-0.771497,0.0,1.0
39,-0.773820,-1.383122,-0.297583,-0.777094,0.0,0.0
40,-0.989577,-0.100900,-0.315786,-0.846411,0.0,0.0
41,-1.008534,-1.320796,-0.384552,-0.857466,1.0,0.0
42,-1.102106,-0.906938,-0.520596,-1.015365,0.0,0.0
43,-1.281134,0.217682,-1.449605,-1.058960,0.0,1.0
44,-1.134305,1.206419,-1.509074,-1.173209,0.0,0.0
45,-1.600350,0.101254,-1.727400,-1.180082,0.0,1.0
46,-1.593413,-0.199322,0.711122,-1.566922,1.0,0.0
47,-1.622362,0.507722,-1.743127,-1.740627,0.0,0.0
48,-1.610433,-2.509409,-1.743127,-1.913212,0.0,1.0
49,-1.622362,-0.157226,-1.369985,-2.439313,0.0,0.0

In [18]:
X = df.drop('Profit', axis=1)
y = df['Profit']

In [23]:
x = clean_df.drop('Profit', axis=1)
y = clean_df['Profit']

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

ValueError: could not convert string to float: 'Florida'

In [26]:
from joblib import dump, load # dump and load are used to save and load the model respectively
with open('models/multi_linear_model.joblib', 'wb') as f:
    dump(regressor, f)
    print("Model dumped successfully.")

Model dumped successfully.